AWSTemplateFormatVersion: "2010-09-09"
Description: >
  DIO – AWS Cloud Foundations | Primeira Stack com CloudFormation.
  Provisiona: S3 (logs), CloudTrail (auditoria), IAM Role/InstanceProfile para EC2
  com permissões de monitoramento e um Alarme do CloudWatch para CPU.

Parameters:
  ProjectName:
    Type: String
    Default: dio-cloudformation-foundations
    Description: Prefixo para nomear recursos.
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t2.micro, t3.micro]
    Description: Tipo da instância EC2 para o ambiente de demonstração.
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: AMI do Amazon Linux via SSM (sempre atual).

Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-logs-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Permite que o CloudTrail grave objetos no bucket de logs
          - Sid: CloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${LogsBucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: CloudTrailBucketList
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt LogsBucket.Arn

  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn: LogsBucketPolicy
    Properties:
      TrailName: !Sub "${ProjectName}-trail"
      S3BucketName: !Ref LogsBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true

  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-ec2-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Permite que a instância publique métricas/logs básicos no CloudWatch
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: cw-basic-inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudwatch:PutMetricData
                Resource: "*"

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${ProjectName}-ec2-profile"
      Roles: [!Ref Ec2Role]

  DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2InstanceProfile
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ec2"

  CpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cpu-alarm"
      AlarmDescription: "Alarme quando CPU da instância EC2 > 70% por 2 períodos."
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: InstanceId
          Value: !Ref DemoInstance

Outputs:
  oBucketLogs:
    Description: Bucket S3 que armazena os logs do CloudTrail.
    Value: !Ref LogsBucket
    Export:
      Name: !Sub "${ProjectName}-logs-bucket"
  oTrailName:
    Description: Nome da trilha de auditoria do CloudTrail.
    Value: !Ref Trail
  oInstanceId:
    Description: ID da instância EC2 provisionada.
    Value: !Ref DemoInstance
  oCpuAlarm:
    Description: Nome do alarme de CPU no CloudWatch.
    Value: !Ref CpuAlarm
  oRegion:
    Description: Região em que a stack foi criada.
    Value: !Ref "AWS::Region"
